development:
  adapter: postgresql
  database: rumblr #or whatever your db is called

  production:
  adapter: postgresql
  host: <%= ENV['postgres://aqstlklduuxofa:98f1875ab41f051225af9c29679398d5c04ade00707ee9ec022a223252f29478@ec2-54-204-46-236.compute-1.amazonaws.com:5432/dan2jmvdkdskai'] %> #This is an env variable that Heroku creates for us. Can be found in your settings config vars
