development:
  adapter: postgresql
  database: rumblr #or whatever your db is called

  production:
  adapter: postgresql
  host: <%= ENV['postgres://hndevgnkivugeu:567584b5d3ea8005939d9e6dfa6005586951a67a999b166701af2b87056e11c6@ec2-54-83-204-6.compute-1.amazonaws.com:5432/daopchtkk6v9ub'] %> #This is an env variable that Heroku creates for us. Can be found in your settings config vars
